export const GET_PAGE_SOURCE_SUCCESS = "GET_PAGE_SOURCE_SUCCESS";
export const GET_PAGE_SOURCE_FAILURE = "GET_PAGE_SOURCE_FAILURE";
// export const GET_PAGE_SOURCE = "GET_PAGE_SOURCE";
export const PAGE_SOURCE_SUMMARY_FAILURE = "PAGE_SOURCE_SUMMARY_FAILURE";
export const PAGE_SOURCE_SUMMARY_SUCCESS = "PAGE_SOURCE_SUMMARY_SUCCESS";
